### ISSUE TITLE
Create schema

### ISSUE THREAD

**Issue by x64-tech** [x64-Technology/project001#5]
Create schema for USER and POST 

User schema whill have 

**basic info**
- name 
- email
- username
- Password

**additional info**
- birthday 
- gender
- profession

**Comment by dvip1** [comment]
can do that, assign it to me

**Comment by x64-tech** [comment]
Alright issue is fixed.. 👍

**Comment by x64-tech** [comment]
Well done @dvip1 to resolve this issue..
